include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    unused_import: error
    unused_local_variable: warning

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_final_locals: true
    unawaited_futures: true
    sort_child_properties_last: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
