CREATE TABLE admin_accounts (
    admin_id uuid NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(512) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    role character varying(20) NOT NULL,
    "Permissions" text[] NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    is_2fa_enabled boolean NOT NULL DEFAULT FALSE,
    totp_secret character varying(256),
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    last_login_at timestamp with time zone,
    last_login_ip character varying(50),
    "FailedLoginAttempts" integer NOT NULL DEFAULT 0,
    "LockoutEnd" timestamp with time zone,
    CONSTRAINT "PK_admin_accounts" PRIMARY KEY (admin_id)
);


CREATE TABLE auth_challenges (
    "ChallengeId" uuid NOT NULL,
    "AccountType" character varying(20) NOT NULL,
    "AccountId" uuid,
    "Email" character varying(255) NOT NULL,
    "ChallengeType" character varying(40) NOT NULL,
    "SecretHash" character varying(128) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "ConsumedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_auth_challenges" PRIMARY KEY ("ChallengeId")
);


CREATE TABLE "Categories" (
    "CategoryId" uuid NOT NULL,
    "Name" text NOT NULL,
    "IconData" text,
    "Color" text,
    "Description" text,
    "ParentCategoryId" uuid,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId"),
    CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("CategoryId")
);


CREATE TABLE "MediaAssets" (
    "AssetId" uuid NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "ContentType" character varying(255) NOT NULL,
    "Data" bytea,
    "RelatedId" uuid,
    "AssetType" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MediaAssets" PRIMARY KEY ("AssetId")
);


CREATE TABLE platform_rules (
    rule_id uuid NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "Description" text,
    "Group" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_platform_rules" PRIMARY KEY (rule_id)
);


CREATE TABLE refresh_tokens (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" character varying(255) NOT NULL,
    "UserId" uuid NOT NULL,
    "Role" character varying(20) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByIp" character varying(50),
    "ReplacedByToken" character varying(255),
    CONSTRAINT "PK_refresh_tokens" PRIMARY KEY ("Id")
);


CREATE TABLE "Tags" (
    "TagId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Type" text,
    "Color" text,
    "IconData" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("TagId")
);


CREATE TABLE "Users" (
    "UserId" uuid NOT NULL,
    "FirebaseUid" text,
    "Email" text,
    "PhoneNumber" text,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "ProfilePhotoData" text,
    "FcmToken" text,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "Status" integer NOT NULL,
    "StatusReason" text,
    "SuspendedUntil" timestamp with time zone,
    "StatusChangedAt" timestamp with time zone,
    "LastLatitude" double precision,
    "LastLongitude" double precision,
    "TotalSaved" double precision NOT NULL,
    "TotalKm" double precision NOT NULL,
    "TotalTrips" integer NOT NULL,
    "PasswordHash" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "LastLoginIp" text,
    "FailedLoginAttempts" integer NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "Is2FAEnabled" boolean NOT NULL,
    "TotpSecret" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);


CREATE TABLE audit_logs (
    audit_id uuid NOT NULL,
    admin_id uuid NOT NULL,
    action character varying(100) NOT NULL,
    target_entity character varying(100) NOT NULL,
    target_id character varying(255) NOT NULL,
    changes jsonb,
    timestamp timestamp with time zone NOT NULL DEFAULT (NOW()),
    ip_address character varying(50),
    user_agent text,
    CONSTRAINT "PK_audit_logs" PRIMARY KEY (audit_id),
    CONSTRAINT "FK_audit_logs_admin_accounts_admin_id" FOREIGN KEY (admin_id) REFERENCES admin_accounts (admin_id) ON DELETE CASCADE
);


CREATE TABLE error_logs (
    log_id uuid NOT NULL,
    timestamp timestamp with time zone NOT NULL DEFAULT (NOW()),
    error_type character varying(100) NOT NULL,
    message text NOT NULL,
    stack_trace text,
    user_id uuid,
    endpoint character varying(500),
    http_method character varying(10),
    severity character varying(10) NOT NULL,
    resolved boolean NOT NULL DEFAULT FALSE,
    resolved_by uuid,
    resolved_at timestamp with time zone,
    CONSTRAINT "PK_error_logs" PRIMARY KEY (log_id),
    CONSTRAINT "FK_error_logs_admin_accounts_resolved_by" FOREIGN KEY (resolved_by) REFERENCES admin_accounts (admin_id)
);


CREATE TABLE moderation_queue (
    item_id uuid NOT NULL,
    content_type character varying(20) NOT NULL,
    title character varying(500) NOT NULL,
    preview text,
    reference_id uuid NOT NULL,
    submitted_by uuid NOT NULL,
    submitted_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    status character varying(20) NOT NULL DEFAULT 'pending',
    report_count integer NOT NULL DEFAULT 0,
    "FlagReasons" text[] NOT NULL,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    rejection_reason text,
    CONSTRAINT "PK_moderation_queue" PRIMARY KEY (item_id),
    CONSTRAINT "FK_moderation_queue_admin_accounts_reviewed_by" FOREIGN KEY (reviewed_by) REFERENCES admin_accounts (admin_id)
);


CREATE TABLE user_reports (
    report_id uuid NOT NULL,
    reported_item_id character varying(255) NOT NULL,
    item_type character varying(20) NOT NULL,
    reported_by uuid NOT NULL,
    reason character varying(30) NOT NULL,
    comments text,
    "Evidence" text[] NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    status character varying(20) NOT NULL DEFAULT 'pending',
    handled_by uuid,
    resolution_note text,
    resolved_at timestamp with time zone,
    CONSTRAINT "PK_user_reports" PRIMARY KEY (report_id),
    CONSTRAINT "FK_user_reports_admin_accounts_handled_by" FOREIGN KEY (handled_by) REFERENCES admin_accounts (admin_id)
);


CREATE TABLE "Journeys" (
    "JourneyId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Status" text NOT NULL,
    "Type" text NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "StartName" text,
    "StartLat" double precision NOT NULL,
    "StartLng" double precision NOT NULL,
    "EndName" text,
    "EndLat" double precision,
    "EndLng" double precision,
    "Distance" double precision NOT NULL,
    "Duration" bigint NOT NULL,
    "TagsJson" text,
    "ShopsJson" text,
    "OffersRedeemed" integer NOT NULL,
    "TotalSavings" numeric NOT NULL,
    "LikesCount" integer NOT NULL,
    "ViewsCount" integer NOT NULL,
    "PathJson" text,
    CONSTRAINT "PK_Journeys" PRIMARY KEY ("JourneyId"),
    CONSTRAINT "FK_Journeys_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "Keepers" (
    "KeeperId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "BusinessName" text NOT NULL,
    "BusinessLicense" text,
    "GstNumber" text,
    "PanNumber" text,
    "DocumentData" text,
    "SocialLinksJson" text,
    "Status" integer NOT NULL,
    "RejectionReason" text,
    "HoldReason" text,
    "HoldUntil" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ApprovedAt" timestamp with time zone,
    "IdentityProofType" text,
    "IdentityProofNumber" text,
    "IdentityProofImage" bytea,
    "BusinessLicenseNumber" text,
    "BusinessLicenseImage" bytea,
    "GstCertificateImage" bytea,
    "PanCardImage" bytea,
    "AddressProofType" text,
    "AddressProofImage" bytea,
    "ShopFrontImage" bytea,
    "ShopInsideImage" bytea,
    "VerificationNotes" text,
    "IsVerified" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Keepers" PRIMARY KEY ("KeeperId"),
    CONSTRAINT "FK_Keepers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE route_records (
    route_id uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "StartLatitude" double precision NOT NULL,
    "StartLongitude" double precision NOT NULL,
    "StartAddress" text,
    "EndLatitude" double precision NOT NULL,
    "EndLongitude" double precision NOT NULL,
    "EndAddress" text,
    "DistanceKm" double precision,
    "EstimatedMinutes" integer,
    "Status" integer NOT NULL,
    "OffersFoundOnRoute" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_route_records" PRIMARY KEY (route_id),
    CONSTRAINT "FK_route_records_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "SupportTickets" (
    "TicketId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Role" text NOT NULL,
    "Subject" text NOT NULL,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("TicketId"),
    CONSTRAINT "FK_SupportTickets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE chat_threads (
    "ThreadId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "KeeperId" uuid NOT NULL,
    "Status" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "LastMessageAt" timestamp with time zone,
    CONSTRAINT "PK_chat_threads" PRIMARY KEY ("ThreadId"),
    CONSTRAINT "FK_chat_threads_Keepers_KeeperId" FOREIGN KEY ("KeeperId") REFERENCES "Keepers" ("KeeperId") ON DELETE CASCADE,
    CONSTRAINT "FK_chat_threads_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE keeper_audit_schedules (
    "AuditScheduleId" uuid NOT NULL,
    "KeeperId" uuid NOT NULL,
    "RequestedByAdminId" uuid NOT NULL,
    "AuditDate" timestamp with time zone NOT NULL,
    "Notes" text,
    "Status" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_keeper_audit_schedules" PRIMARY KEY ("AuditScheduleId"),
    CONSTRAINT "FK_keeper_audit_schedules_Keepers_KeeperId" FOREIGN KEY ("KeeperId") REFERENCES "Keepers" ("KeeperId") ON DELETE CASCADE,
    CONSTRAINT "FK_keeper_audit_schedules_admin_accounts_RequestedByAdminId" FOREIGN KEY ("RequestedByAdminId") REFERENCES admin_accounts (admin_id) ON DELETE RESTRICT
);


CREATE TABLE keeper_documents (
    "DocumentId" uuid NOT NULL,
    "KeeperId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "DocumentType" character varying(100) NOT NULL,
    "DocumentReference" text NOT NULL,
    "Status" character varying(30) NOT NULL,
    "ReviewNotes" text,
    "ReviewedByAdminId" uuid,
    "ReviewedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_keeper_documents" PRIMARY KEY ("DocumentId"),
    CONSTRAINT "FK_keeper_documents_Keepers_KeeperId" FOREIGN KEY ("KeeperId") REFERENCES "Keepers" ("KeeperId") ON DELETE CASCADE,
    CONSTRAINT "FK_keeper_documents_admin_accounts_ReviewedByAdminId" FOREIGN KEY ("ReviewedByAdminId") REFERENCES admin_accounts (admin_id) ON DELETE SET NULL
);


CREATE TABLE keeper_review_messages (
    "MessageId" uuid NOT NULL,
    "KeeperId" uuid NOT NULL,
    "AdminId" uuid NOT NULL,
    "MessageType" character varying(50) NOT NULL,
    "Message" text NOT NULL,
    "IsReadByKeeper" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_keeper_review_messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_keeper_review_messages_Keepers_KeeperId" FOREIGN KEY ("KeeperId") REFERENCES "Keepers" ("KeeperId") ON DELETE CASCADE,
    CONSTRAINT "FK_keeper_review_messages_admin_accounts_AdminId" FOREIGN KEY ("AdminId") REFERENCES admin_accounts (admin_id) ON DELETE RESTRICT
);


CREATE TABLE "Shops" (
    "ShopId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Address" text,
    "PhoneNumber" text,
    "Email" text,
    "KeeperId" uuid NOT NULL,
    "Latitude" double precision,
    "Longitude" double precision,
    "GooglePlaceId" text,
    "CategoryId" uuid,
    "ImageData" bytea,
    "ShopProfileImage" bytea,
    "ShopImages" bytea[] NOT NULL DEFAULT (ARRAY[]::bytea[]),
    "IsOpen" boolean NOT NULL,
    "BusinessHoursJson" text,
    "Amenities" text[] NOT NULL DEFAULT (ARRAY[]::text[]),
    "NotificationRadius" double precision,
    "AdminNotes" text,
    "Tags" text[] NOT NULL DEFAULT (ARRAY[]::text[]),
    "IsVerified" boolean NOT NULL,
    "VerifyStatus" character varying(50) NOT NULL DEFAULT 'Pending',
    "IsActive" boolean NOT NULL,
    "RejectionReason" text,
    "DeactivateReason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Shops" PRIMARY KEY ("ShopId"),
    CONSTRAINT "CK_Shops_VerifyStatus" CHECK ("VerifyStatus" IN ('Pending', 'Verified', 'Rejected')),
    CONSTRAINT "FK_Shops_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId"),
    CONSTRAINT "FK_Shops_Keepers_KeeperId" FOREIGN KEY ("KeeperId") REFERENCES "Keepers" ("KeeperId") ON DELETE CASCADE
);


CREATE TABLE "SupportTicketMessages" (
    "MessageId" uuid NOT NULL,
    "TicketId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "SenderRole" text NOT NULL,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SupportTicketMessages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_SupportTicketMessages_SupportTickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "SupportTickets" ("TicketId") ON DELETE CASCADE
);


CREATE TABLE chat_messages (
    "MessageId" uuid NOT NULL,
    "ThreadId" uuid NOT NULL,
    "SenderType" character varying(20) NOT NULL,
    "SenderId" uuid,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_chat_messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_chat_messages_chat_threads_ThreadId" FOREIGN KEY ("ThreadId") REFERENCES chat_threads ("ThreadId") ON DELETE CASCADE
);


CREATE TABLE "Offers" (
    "OfferId" uuid NOT NULL,
    "ShopId" uuid NOT NULL,
    "KeeperId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "TermsAndConditions" text,
    "DiscountPercentage" numeric,
    "DiscountAmount" numeric,
    "MinOrderValue" numeric,
    "CouponCode" text,
    "ImageData" bytea,
    "Tags" text[] NOT NULL,
    "IsFlashSale" boolean NOT NULL,
    "StockQuantity" integer,
    "AvailableFromTime" interval,
    "AvailableToTime" interval,
    "CategoryId" uuid,
    "Status" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Offers" PRIMARY KEY ("OfferId"),
    CONSTRAINT "FK_Offers_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId"),
    CONSTRAINT "FK_Offers_Keepers_KeeperId" FOREIGN KEY ("KeeperId") REFERENCES "Keepers" ("KeeperId") ON DELETE CASCADE,
    CONSTRAINT "FK_Offers_Shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES "Shops" ("ShopId") ON DELETE CASCADE
);


CREATE TABLE "ShopNotificationSettings" (
    "SettingId" uuid NOT NULL,
    "ShopId" uuid NOT NULL,
    "AutoRadiusNotification" boolean NOT NULL,
    "RadiusKm" numeric NOT NULL,
    "CooldownHours" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShopNotificationSettings" PRIMARY KEY ("SettingId"),
    CONSTRAINT "FK_ShopNotificationSettings_Shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES "Shops" ("ShopId") ON DELETE CASCADE
);


CREATE TABLE "Favourites" (
    "FavouriteId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ShopId" uuid,
    "OfferId" uuid,
    "Type" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Favourites" PRIMARY KEY ("FavouriteId"),
    CONSTRAINT "FK_Favourites_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "Offers" ("OfferId"),
    CONSTRAINT "FK_Favourites_Shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES "Shops" ("ShopId"),
    CONSTRAINT "FK_Favourites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE "Notifications" (
    "NotificationId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "ImageUrl" text,
    "Type" integer NOT NULL,
    "Priority" integer NOT NULL,
    "SenderType" text NOT NULL,
    "SenderId" uuid,
    "ShopId" uuid,
    "OfferId" uuid,
    "RadiusKm" numeric,
    "Latitude" numeric,
    "Longitude" numeric,
    "IsGlobal" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "TargetAudience" text NOT NULL,
    "Status" integer NOT NULL,
    "ScheduledAt" timestamp with time zone,
    "SentAt" timestamp with time zone,
    "ExpiresAt" timestamp with time zone,
    "UserId" uuid,
    "IsRead" boolean NOT NULL,
    "SentById" uuid,
    "SentByAdminAdminId" uuid,
    "RecipientCount" integer NOT NULL,
    "MetadataJson" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId"),
    CONSTRAINT "FK_Notifications_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "Offers" ("OfferId"),
    CONSTRAINT "FK_Notifications_Shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES "Shops" ("ShopId"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_Notifications_admin_accounts_SentByAdminAdminId" FOREIGN KEY ("SentByAdminAdminId") REFERENCES admin_accounts (admin_id)
);


CREATE TABLE "Reviews" (
    "ReviewId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ShopId" uuid,
    "OfferId" uuid,
    "Rating" integer NOT NULL,
    "Comment" text,
    "Status" integer NOT NULL,
    "Reply" text,
    "RepliedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "Offers" ("OfferId"),
    CONSTRAINT "FK_Reviews_Shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES "Shops" ("ShopId"),
    CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE notification_delivery_jobs (
    "JobId" uuid NOT NULL,
    "NotificationId" uuid NOT NULL,
    "Status" character varying(30) NOT NULL,
    "ScheduledFor" timestamp with time zone NOT NULL,
    "EnqueuedAt" timestamp with time zone,
    "StartedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "FailedAt" timestamp with time zone,
    "FailureReason" text,
    "AttemptCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_notification_delivery_jobs" PRIMARY KEY ("JobId"),
    CONSTRAINT "FK_notification_delivery_jobs_Notifications_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "Notifications" ("NotificationId") ON DELETE CASCADE
);


CREATE TABLE "NotificationLogs" (
    "LogId" uuid NOT NULL,
    "NotificationId" uuid NOT NULL,
    "UserId" uuid,
    "Status" text NOT NULL,
    "FailureReason" text,
    "SentAt" timestamp with time zone NOT NULL,
    "DeliveredAt" timestamp with time zone,
    CONSTRAINT "PK_NotificationLogs" PRIMARY KEY ("LogId"),
    CONSTRAINT "FK_NotificationLogs_Notifications_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "Notifications" ("NotificationId") ON DELETE CASCADE,
    CONSTRAINT "FK_NotificationLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId")
);


CREATE TABLE "UserNotifications" (
    "UserNotificationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "NotificationId" uuid NOT NULL,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "SentAt" timestamp with time zone,
    "DeliveryStatus" text NOT NULL,
    CONSTRAINT "PK_UserNotifications" PRIMARY KEY ("UserNotificationId"),
    CONSTRAINT "FK_UserNotifications_Notifications_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "Notifications" ("NotificationId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserNotifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_admin_accounts_email" ON admin_accounts (email);


CREATE INDEX "IX_audit_logs_admin_id" ON audit_logs (admin_id);


CREATE INDEX "IX_audit_logs_timestamp" ON audit_logs (timestamp DESC);


CREATE INDEX "IX_auth_challenges_Email_ChallengeType_ConsumedAt" ON auth_challenges ("Email", "ChallengeType", "ConsumedAt");


CREATE INDEX "IX_auth_challenges_ExpiresAt" ON auth_challenges ("ExpiresAt");


CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");


CREATE INDEX "IX_chat_messages_ThreadId" ON chat_messages ("ThreadId");


CREATE INDEX "IX_chat_threads_KeeperId" ON chat_threads ("KeeperId");


CREATE UNIQUE INDEX "IX_chat_threads_UserId_KeeperId" ON chat_threads ("UserId", "KeeperId");


CREATE INDEX "IX_error_logs_resolved" ON error_logs (resolved);


CREATE INDEX "IX_error_logs_resolved_by" ON error_logs (resolved_by);


CREATE INDEX "IX_error_logs_severity" ON error_logs (severity);


CREATE INDEX "IX_Favourites_OfferId" ON "Favourites" ("OfferId");


CREATE INDEX "IX_Favourites_ShopId" ON "Favourites" ("ShopId");


CREATE INDEX "IX_Favourites_UserId" ON "Favourites" ("UserId");


CREATE INDEX "IX_Journeys_UserId" ON "Journeys" ("UserId");


CREATE INDEX "IX_keeper_audit_schedules_KeeperId" ON keeper_audit_schedules ("KeeperId");


CREATE INDEX "IX_keeper_audit_schedules_RequestedByAdminId" ON keeper_audit_schedules ("RequestedByAdminId");


CREATE INDEX "IX_keeper_documents_KeeperId" ON keeper_documents ("KeeperId");


CREATE INDEX "IX_keeper_documents_ReviewedByAdminId" ON keeper_documents ("ReviewedByAdminId");


CREATE INDEX "IX_keeper_review_messages_AdminId" ON keeper_review_messages ("AdminId");


CREATE INDEX "IX_keeper_review_messages_KeeperId" ON keeper_review_messages ("KeeperId");


CREATE INDEX "IX_Keepers_UserId" ON "Keepers" ("UserId");


CREATE INDEX "IX_moderation_queue_content_type" ON moderation_queue (content_type);


CREATE INDEX "IX_moderation_queue_reviewed_by" ON moderation_queue (reviewed_by);


CREATE INDEX "IX_moderation_queue_status" ON moderation_queue (status);


CREATE INDEX "IX_notification_delivery_jobs_NotificationId_Status" ON notification_delivery_jobs ("NotificationId", "Status");


CREATE INDEX "IX_notification_delivery_jobs_ScheduledFor" ON notification_delivery_jobs ("ScheduledFor");


CREATE INDEX "IX_NotificationLogs_NotificationId" ON "NotificationLogs" ("NotificationId");


CREATE INDEX "IX_NotificationLogs_UserId" ON "NotificationLogs" ("UserId");


CREATE INDEX "IX_Notifications_OfferId" ON "Notifications" ("OfferId");


CREATE INDEX "IX_Notifications_SentByAdminAdminId" ON "Notifications" ("SentByAdminAdminId");


CREATE INDEX "IX_Notifications_ShopId" ON "Notifications" ("ShopId");


CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");


CREATE INDEX "IX_Offers_CategoryId" ON "Offers" ("CategoryId");


CREATE INDEX "IX_Offers_KeeperId" ON "Offers" ("KeeperId");


CREATE INDEX "IX_Offers_ShopId" ON "Offers" ("ShopId");


CREATE INDEX "IX_Reviews_OfferId" ON "Reviews" ("OfferId");


CREATE INDEX "IX_Reviews_ShopId" ON "Reviews" ("ShopId");


CREATE INDEX "IX_Reviews_UserId" ON "Reviews" ("UserId");


CREATE INDEX "IX_route_records_UserId" ON route_records ("UserId");


CREATE INDEX "IX_ShopNotificationSettings_ShopId" ON "ShopNotificationSettings" ("ShopId");


CREATE INDEX "IX_Shops_CategoryId" ON "Shops" ("CategoryId");


CREATE INDEX "IX_Shops_KeeperId" ON "Shops" ("KeeperId");


CREATE INDEX "IX_SupportTicketMessages_TicketId" ON "SupportTicketMessages" ("TicketId");


CREATE INDEX "IX_SupportTickets_UserId" ON "SupportTickets" ("UserId");


CREATE INDEX "IX_user_reports_handled_by" ON user_reports (handled_by);


CREATE INDEX "IX_UserNotifications_NotificationId" ON "UserNotifications" ("NotificationId");


CREATE INDEX "IX_UserNotifications_UserId" ON "UserNotifications" ("UserId");


